# Default values for azure-managed-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## AKS cluster configuration

## The subscription ID
subscriptionID: ""

identity:
  clientId: ""
  tenantId: ""
  clusterIdentityName: "cluster-identity"
  clusterIdentitySecretName: "cluster-identity-secret"
  clusterIdentitySecretNamespace: "default"


cluster:

  ## The resource group for the AKS cluster object
  resourceGroupName: aksclusters

  ## The resource group name for the nodes
  nodeResourceGroupName: base

  ## The location of the cluster
  location: westeurope

  ## The name of the cluster
  name: aks-cluster-api

  ## the subnet
  cidrBlocks:
  - 192.168.0.0/16

aad:
  adminGroupObjectIDs:
  - insert-admin-group-id

controlplane:
  ## SSH public key (must be valid)
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIOxg+goSYoCIND3IIAjPoPGr7gsux9OQjE5IP2wEU8eMsywgGXBwZXUVjh8NgFHVWZEMTQCAM52P2ipYBup9QhuqWVjH4v0hrj1X/rx7tzlZh2wk3kgVPQwMKCyacQLifqus4quJLSQAPu1ksgxaWEBWnSa0e+DM2D0PYs/j284qOO9T9ULqpb/ZJK9gySa+AfSMhGCskcT/EfE8g1iqC96PajFxGHOBxqiDFtIKPhNiqKYruDhVJYmhAXG6ScHadiXzP3BdiPR66eyCOQtSeIxjnEeJcrZ7vZLFpWQvaaZw+JfPkGGFCsBTn39dfr1awrMtPIPvkj4iU1jkGKzUD alessandro@Alessandros-MBP.fritz.box"

  ## Kubernetes version
  kubernetes_version: "v1.24.6"

  ## Network policy, "calico" (for kubenet and azurecni) or "azure" (for azureCNI)
  networkPolicy: "calico"

  ## Network Plugin "kubenet" or "azure"
  networkPlugin: "azure"

  ## vnetcidr
  vnetcidr: "-insert-vnet-cidr-"

  ## vnetname
  vnetname: "-insert-vnet-name-"

  ## vnetrg
  vnetrg: "-insert-vnet-resource-group-"

  ## subnetcidr
  subnetcidr: "-insert-subnet-cidr-"

  ## subnetname
  subnetname: "-insert-subnet-name-"


#Only 1 Nodepool of mode System is allowed
agentpools:
 - name: agentpool0
   mode: System
   sku: Standard_B4ms
   nodecount: 2
   osDiskSizeGB: 100
 - name: agentpool1
   mode: User
   nodecount: 2
   sku: Standard_B4ms
   osDiskSizeGB: 100
